### ISSUE TITLE
Error ingesting resources

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-aws#11]
We see this error when ingesting resources. Is this a known bug?

```
fatal error: concurrent map read and map write

goroutine 88897 [running]:
runtime.throw(0x37784f6, 0x21)
	/opt/hostedtoolcache/go/1.15.8/x64/src/runtime/panic.go:1116 +0x72 fp=0xc002814ca0 sp=0xc002814c70 pc=0x435f52
runtime.mapaccess1_faststr(0x33a1620, 0xc00224b800, 0xc000074820, 0xd, 0xc00026e088)
	/opt/hostedtoolcache/go/1.15.8/x64/src/runtime/map_faststr.go:21 +0x465 fp=0xc002814d10 sp=0xc002814ca0 pc=0x413c45
github.com/cloudquery/cq-provider-aws/provider.(*Provider).collectResource(0xc0003c97c0, 0xc000074820, 0x16, 0x33a2280, 0x0, 0xc0000b0960, 0x0)
	/home/runner/work/cq-provider-aws/cq-provider-aws/provider/provider.go:327 +0x177 fp=0xc002814f30 sp=0xc002814d10 pc=0x313e577
github.com/cloudquery/cq-provider-aws/provider.(*Provider).Fetch.func4(0x1, 0x0)
	/home/runner/work/cq-provider-aws/cq-provider-aws/provider/provider.go:276 +0x51 fp=0xc002814f78 sp=0xc002814f30 pc=0x313f451
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0027c0c60, 0xc0027c0d20)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x59 fp=0xc002814fd0 sp=0xc002814f78 pc=0xc7c9d9
runtime.goexit()
	/opt/hostedtoolcache/go/1.15.8/x64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc002814fd8 sp=0xc002814fd0 pc=0x46b281
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```

Thanks

**Comment by yevgenypats** [comment]
@xino12 Thanks for opening this. I pushed a fix https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.2.4 . Let me know if that helps.
