### ISSUE TITLE
NPE when ingesting s3 buckets

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-aws#140]
I see this error when trying to ingest s3 bukets, are you already aware of this?

```
30AM DBG resolving table relation @module=aws account_id=324405309526 relation=aws_route53_hosted_zone_query_logging_configs table=aws_route53_hosted_zones timestamp=2021-08-10T06:30:47.734Z
6:30AM DBG panic: runtime error: invalid memory address or nil pointer dereference
6:30AM DBG [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3d016b9]
6:30AM DBG 
6:30AM DBG goroutine 2963 [running]:
6:30AM DBG github.com/cloudquery/cq-provider-aws/resources.resolveS3BucketsAttributes(0x4b2e400, 0xc001152380, 0x4a30c40, 0xc001391880, 0xc00137e440, 0x0, 0x4b2e400)
6:30AM DBG 	/home/runner/work/cq-provider-aws/cq-provider-aws/resources/s3_buckets.go:450 +0x12b9
6:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.resolveResourceValues(0xc000411e00, 0x4b2e7c0, 0xc000584018, 0x4b49a60, 0xc0004dd080, 0x0, 0x4b2e400, 0xc001152380, 0x4a30c40, 0xc001391880, ...)
6:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.2.1/provider/schema/execution.go:147 +0x126
6:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.resolveResources(0xc000411e00, 0x4b2e7c0, 0xc000584018, 0x4b49a60, 0xc0004dd080, 0x0, 0x4b2e400, 0xc001152380, 0x4a30c40, 0xc001391880, ...)
6:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.2.1/provider/schema/execution.go:114 +0x1df
6:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.callTableResolve(0xc000411e00, 0x4b2e7c0, 0xc000584018, 0x4b49a60, 0xc0004dd080, 0x0, 0x4b2e400, 0xc001152380, 0x4a30c40, 0xc001391880, ...)
6:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.2.1/provider/schema/execution.go:93 +0x232
6:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.ResolveTable.func1(0x0, 0x0)
6:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.2.1/provider/schema/execution.go:51 +0xc5
6:30AM DBG golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00109c240, 0xc00117e180)
6:30AM DBG 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
6:30AM DBG created by golang.org/x/sync/errgroup.(*Group).Go
6:30AM DBG 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
2021/08/10 06:30:47 Client closed local connection on 127.0.0.1:5432

```

**Comment by roneli** [comment]
Hi, I am noticing you are using a very old provider with an old sdk v0.2.1 version.

I suggest trying [v0.5.5](https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.5.5) version. 

if you need any help with upgrading your the provider from the previous version, feel free to ping me.
