### ISSUE TITLE
Issue with CloudWatch and Neo4j

### ISSUE THREAD

**Issue by francilioaraujo** [cloudquery/cq-provider-aws#25]
An error ocurrs when fetching cloudwatch.alarms and saving them to neo4j on version v0.2.18 (current latest). The debug logs are as follows:

```
2:33PM DBG panic: reflect: call of reflect.Value.Len on ptr Value
2:33PM DBG 
2:33PM DBG goroutine 47 [running]:
2:33PM DBG reflect.Value.Len(0x326d980, 0xc000360568, 0x196, 0x1)
2:33PM DBG 	/opt/hostedtoolcache/go/1.15.10/x64/src/reflect/value.go:1163 +0x185
2:33PM DBG github.com/cloudquery/cloudquery/database.(*Database).neo4jInsertMany(0xc00050c240, 0x326d980, 0xc000360568, 0x196, 0x3cf6aa0, 0xc000718840, 0xc000688140, 0xc000666bc0, 0x9)
2:33PM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cloudquery@v0.11.0/database/neo4j.go:182 +0x10d
2:33PM DBG github.com/cloudquery/cloudquery/database.(*Database).neo4jInsertOne(0xc00050c240, 0x3714be0, 0xc000360480, 0x199, 0x3cf6aa0, 0xc000718840, 0x0, 0x0, 0x0)
2:33PM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cloudquery@v0.11.0/database/neo4j.go:177 +0x14ca
2:33PM DBG github.com/cloudquery/cloudquery/database.(*Database).neo4jInsertMany(0xc00050c240, 0x32d0480, 0xc00069ca60, 0x97, 0x3cf6aa0, 0xc000718840, 0x0, 0x0, 0x0)
2:33PM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cloudquery@v0.11.0/database/neo4j.go:184 +0xde
2:33PM DBG github.com/cloudquery/cloudquery/database.(*Database).ChunkedCreate(0xc00050c240, 0x32d0480, 0xc00069ca60)
2:33PM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cloudquery@v0.11.0/database/database.go:168 +0x2c8
2:33PM DBG github.com/cloudquery/cq-provider-aws/resources/cloudwatch.(*Client).alarms(0xc0002e8ac0, 0x3ce8840, 0xc000544500, 0x33a3480, 0x0, 0x0, 0xc000457448)
2:33PM DBG 	/home/runner/work/cq-provider-aws/cq-provider-aws/resources/cloudwatch/alarms.go:179 +0x1f6
2:33PM DBG github.com/cloudquery/cq-provider-aws/resources/cloudwatch.(*Client).CollectResource(0xc0002e8ac0, 0x3ce8840, 0xc000544500, 0xc00027a58b, 0x6, 0x33a3480, 0x0, 0x100000000000000, 0x0)
2:33PM DBG 	/home/runner/work/cq-provider-aws/cq-provider-aws/resources/cloudwatch/client.go:37 +0x10a
2:33PM DBG github.com/cloudquery/cq-provider-aws/provider.(*Provider).fetchAccount.func2(0x1, 0x0)
2:33PM DBG 	/home/runner/work/cq-provider-aws/cq-provider-aws/provider/provider.go:259 +0x10e
2:33PM DBG golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000716bd0, 0xc00014c070)
2:33PM DBG 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x59
2:33PM DBG created by golang.org/x/sync/errgroup.(*Group).Go
2:33PM DBG 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
Error: rpc error: code = Unavailable desc = transport is closing
```
The account I used has access to cloudwatch alarms.

I suggest adding some documentation on running development versions of this provider, so more newcomers can help on fixes

**Comment by yevgenypats** [comment]
@francilioaraujo Hi Thanks for sharing this - I'll look into it. The Neo4j support is currently really experimental. Just curious, can you try with PostgreSQL does it work on your end? Also, Is there any specific reason/feature you wanted to use Graph/Neo4j instead of the standard PostgreSQL?

**Comment by francilioaraujo** [comment]
@yevgenypats , thank you for your support. With PostgreSQL it works as expected.
I had already made some manual scraping to neo4j and wanted to make similar queries with CloudQuery. One particular query I have is "how many load balancers have empty target groups". With Neo4j this sort of query does not require us to think of a "join path between ELBs and EC2 instances".
But I'm already satisfied with running with PostgreSQL.

Just curious. How do you set a debug environment? Do you use VS Code?

**Comment by roneli** [comment]
Hi, personally I like using GoLand, but it can work fine with VS Code. 

If you would like to setup a debug environment for a specific plugin, you need to set the` CQ_PROVIDER_DEBUG=1` environment variable.
After that you can execute the main.go from the IDE and use it as if it were the cloudquery cli. (i.e fetch etc'). 

The variable sets the the plugin to be current plugin you are working on rather than the latest version released.
Just another side note, you need to have a valid config.yml in the directory you are running the plugin from.

Hope this helps, if you have any more question feel free to ask :).
