### ISSUE TITLE
Error on fetching Cloudwatch Metrics

### ISSUE THREAD

**Issue by daniils-hq** [cloudquery/cq-provider-aws#42]
I'm using the latest `clouquery` version with the latest AWS provider on Mac.
Sadly, query always fails on Cloudwatch Metrics with the following stack trace.
Tried with the different AWS accounts without much success.
```
10:06AM DBG panic: runtime error: invalid memory address or nil pointer dereference
10:06AM DBG [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3a86c7d]
10:06AM DBG
10:06AM DBG goroutine 1235 [running]:
10:06AM DBG github.com/cloudquery/cq-provider-aws/resources.resolveCloudwatchAlarmMetricMetricStatMetricDimensions(0x47cba20, 0xc000491800, 0x4709a20, 0xc000422380, 0xc0004918c0, 0x426e72b, 0x1d, 0xc, 0x0, 0x0, ...)
10:06AM DBG 	/home/runner/work/cq-provider-aws/cq-provider-aws/resources/cloudwatch_alarms.go:244 +0xbd
10:06AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.resolveColumns(0xc00007e380, 0x47cbd20, 0xc000130e60, 0x47e08e0, 0xc000187780, 0x0, 0x47cba20, 0xc000491800, 0x4709a20, 0xc000422380, ...)
10:06AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:148 +0x317
10:06AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.resolveResourceValues(0xc00007e380, 0x47cbd20, 0xc000130e60, 0x47e08e0, 0xc000187780, 0x0, 0x47cba20, 0xc000491800, 0x4709a20, 0xc000422380, ...)
10:06AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:132 +0xba
10:06AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.resolveResources(0xc00007e380, 0x47cbd20, 0xc000130e60, 0x47e08e0, 0xc000187780, 0x0, 0x47cba20, 0xc000491800, 0x4709a20, 0xc000422380, ...)
10:06AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:108 +0x1df
10:06AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.callTableResolve(0xc00007e380, 0x47cbd20, 0xc000130e60, 0x47e08e0, 0xc000187780, 0x0, 0x47cba20, 0xc000491800, 0x4709a20, 0xc000422380, ...)
10:06AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:88 +0x232
10:06AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.ResolveTable.func1(0xc000cd9bf8, 0x0)
10:06AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:48 +0xb3
10:06AM DBG golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000cd9c20, 0xc000da3140)
10:06AM DBG 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
10:06AM DBG created by golang.org/x/sync/errgroup.(*Group).Go
10:06AM DBG 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
Error: rpc error: code = Unavailable desc = transport is closing
10:06AM DBG received EOF, stopping recv loop err="rpc error: code = Unavailable desc = transport is closing"
10:06AM DBG plugin process exited error="exit status 2" path=/cloudquery/.cq/providers/cloudquery/aws/latest-darwin-amd64 pid=17595
```

**Comment by yevgenypats** [comment]
@daniils-hq Thanks for reporting this bug! Should be fixed with https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.3.8
