### ISSUE TITLE
Error ingesting beanstalk environments

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-aws#44]
While ingesting beanstalk environments I see this segmentation fault error:

```
10:30AM DBG panic: runtime error: invalid memory address or nil pointer dereference
10:30AM DBG [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2ea02ec]
10:30AM DBG 
10:30AM DBG goroutine 2922 [running]:
10:30AM DBG github.com/cloudquery/cq-provider-aws/resources.resolveIamVirtualMfaDeviceUserTags(0x3bcd9e0, 0xc0007d7b00, 0x3b0bae0, 0xc000de6e00, 0xc00f985300, 0x363c993, 0x9, 0xc, 0x0, 0x0, ...)
10:30AM DBG 	/home/runner/work/cq-provider-aws/cq-provider-aws/resources/iam_virtual_mfa_devices.go:134 +0xcc
10:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.resolveColumns(0xc0000eea80, 0x3bcdce0, 0xc0001b8e38, 0x3be26e0, 0xc0001fb680, 0x0, 0x3bcd9e0, 0xc0007d7b00, 0x3b0bae0, 0xc000de6e00, ...)
10:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:148 +0x317
10:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.resolveResourceValues(0xc0000eea80, 0x3bcdce0, 0xc0001b8e38, 0x3be26e0, 0xc0001fb680, 0x0, 0x3bcd9e0, 0xc0007d7b00, 0x3b0bae0, 0xc000de6e00, ...)
10:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:132 +0xba
10:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.resolveResources(0xc0000eea80, 0x3bcdce0, 0xc0001b8e38, 0x3be26e0, 0xc0001fb680, 0x0, 0x3bcd9e0, 0xc0007d7b00, 0x3b0bae0, 0xc000de6e00, ...)
10:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:108 +0x1df
10:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.callTableResolve(0xc0000eea80, 0x3bcdce0, 0xc0001b8e38, 0x3be26e0, 0xc0001fb680, 0x0, 0x3bcd9e0, 0xc0007d7b00, 0x3b0bae0, 0xc000de6e00, ...)
10:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:88 +0x232
10:30AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.ResolveTable.func1(0x0, 0x0)
10:30AM DBG 	/home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.1.6/provider/schema/execution.go:48 +0xb3
10:30AM DBG golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000a7f680, 0xc0009cb740)
10:30AM DBG 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
10:30AM DBG created by golang.org/x/sync/errgroup.(*Group).Go
10:30AM DBG 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
```

**Comment by yevgenypats** [comment]
Looks like it's in `iam.virtual_mfa_devices`. Should be fixed in `https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.3.9`
